name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        name: Setup ToolChain
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2
        name: Setup Cache
      - uses: actions/checkout@v2
        name: Checkout
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --all-features
      - name: check1
        run: ls /target/release
